 
CSI_DIVS = ["00 - GENERAL PROJECT REQUIREMENTS", "01 - GENERAL REQUIREMENTS", "02 - EXISTING CONDITIONS", 
           "03 - CONCRETE", "04 - MASONRY", "05 - METALS", "06 - WOOD, PLASTICS, AND COMPOSITES", 
           "07 - THERMAL AND MOISTURE PROTECTION", "08 - OPENINGS", "09 - FINISHES", "10 - SPECIALTIES", 
           "11 - EQUIPMENT", "12 - FURNISHINGS", "13 - SPECIAL CONSTRUCTION", "14 - CONVEYING EQUIPMENT", 
           "21 - FIRE SUPPRESSION", "22 - PLUMBING", "23 - HEATING, VENTILATING, AND AIR CONDITIONING (HVAC)", 
           "25 - INTEGRATED AUTOMATION", "26 - ELECTRICAL", "27 - COMMUNICATIONS", "28 - ELECTRONIC SAFETY AND SECURITY", 
           "31 - EARTHWORK", "32 - EXTERIOR IMPROVEMENTS", "33 - UTILITIES", "40 - PROCESS INTEGRATION", 
           "41 - MATERIAL PROCESSING AND HANDLING EQUIPMENT", "46 - WATER AND WASTEWATER EQUIPMENT"]


